# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
- stage: Build
  displayName: Application Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install 
        npm install jasmine-node
        npm run build --if-present
        npm test
      displayName: 'npm install and build'

###############################################################################

- stage: Archive
  displayName: ArchiveFiles
  jobs:
  - job: Archive
    displayName: Archive
    steps:
    - task: ArchiveFiles@2
      inputs:
          rootFolderOrFile: '$(system.defaultworkingdirectory)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

#################################################################################

- stage: Unit_Test
  displayName: 'Run Unit Testing'
  
  
  jobs:
    - job: 
      pool: 
        vmImage: 'ubuntu-latest'
      steps:
      - task:  Npm@1 
       
        inputs:
          command: custom
          workingDir: '$(system.defaultworkingdirectory)'
          verbose: false
          customCommand: test
        
   
  
        
         
      
    
    